server:
  port: ${SERVER_PORT:59999}

app:
  table:
    order-details: "[Order Details]"

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=NorthWind;encrypt=true;trustServerCertificate=true;connectTimeout=30
    username: DevUser
    password: Hjm$435yVt7a
  jpa:
    properties:
      hibernate:
        default_schema: dbo
  flyway:
    default-schema: dbo
