app:
  table:
    order-details: "[Order Details]"

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=NorthWind;encrypt=true;trustServerCertificate=true;connectTimeout=30
    username: ${DB_USERNAME:DevUser}
    password: ${DB_PASSWORD:Hjm$435yVt7a}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:dbo}
  flyway:
    default-schema: ${DB_SCHEMA:dbo}
