server:
  port: ${SERVER_PORT:59999}

app:
  table:
    order-details: orderdetails
  security:
    provider-url: ${APP_SECURITY_PROVIDER_URL:http://localhost:55001}

otel:
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/northwind
    username: DevUser
    password: Pwo_698UVtra
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: pilot
  flyway:
    default-schema: pilot
