app:
  table:
    order-details: orderdetails

otel:
  resource:
    attributes:
      deployment.environment: ${OTEL_DEPLOYMENT_ENVIRONMENT:production}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://local-postgres:5432/northwind}
    username: ${DB_USERNAME:DevUser}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:pilot}
  flyway:
    default-schema: ${DB_SCHEMA:pilot}
