app:
  table:
    order-details: "[Order Details]"

spring:
  datasource:
    url: jdbc:sqlserver://local-mssql:1433;databaseName=NorthWind;encrypt=true;trustServerCertificate=true;connectTimeout=30
    username: ${DB_USERNAME:DevUser}
    password: ${DB_PASSWORD:}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:dbo}
  flyway:
    default-schema: ${DB_SCHEMA:dbo}
